language: python
script:
- python -m pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: dViMdniEavAaYXMVHGhh9hSj/k8Fng+gv1BnV50Tm62SWExq1/W9F5F3PlPHYyEzMS7fMsIG5PnMVEzDZ8WWYClQDhfWHP+UwHKKfUXAlUZOsXd+TqlXMT22ptkbaDDkIG6p8/J73lU8FlavMWBusamflD2ctz/4yVceiVNTzDnFa6qxSlc+w/k3f9kXit+iwaadXBB2/NiSkRujuk5b2H2h/v59jKTM/ykA/L0hk60z/ewTlsQQ/XNM8AEe4zB+RGbTW//L+pIqF3/mR6f0p/2WMbMJ8yT1VueUx3Biw9xC+Q+Gn14oR01lqM2iNKOapcc2914UrTG/plXXveBS19JA/UIRr2XXzTrQluP0AtanLnTstREr+4+hmoLVklOz3462HNobuaEa9Mo5kYpsoEiZiEY+esggoPKWK85y4DPgdGDiUBm7fj4gDb/d77oktUkit4T/iocoz1Cy2y+xfzLqkR+H5dS0Q474rgVOBxfWcekGmugRJwJ53xICx/eFdlFjTAbQvtbIHC65soGccbqgnfO3NQKIKFQ9WHre/s7vbUxjEytthT5y6fCbEnVeL6lc7sS8iUlNasxJa9rrfoylvidPJ6oSj76uVYYCvF59rI7+ctNP2f3PRqGuOHpdq8ZGeg6LiPN3AqF+DQEq5oKplQjOG3hK166eOkt4NMU=
